version: 2.1
jobs:
  build:
    docker:
      - image: alpine:3.7
    steps:
      - checkout
      - run:
          name: First Step
          command: | 
            echo 'Hello World'
            echo 'This is the delivery pipeline'
      - run:
          name: Code arrived
          command: |
            ls -al