version: 2.1
jobs:
  build:
    docker:
      - image: circle-ci/node:10-browsers
    steps:
      - checkout
      - run:
          name: First Step
          command: | 
            echo 'Hello World'
            echo 'This is the delivery pipeline'
      - run:
          name: Code arrived
          command: |
            ls -al
      - run:
          name: Running in a unique container
          command: |
            node -v